modLoader="javafml" #mandatory
loaderVersion="${forge_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/ChiefArug/tinkerjs_kubestruct" #optional
[[mods]] #mandatory
modId="tinkerjs_kubestruct" #mandatory
version="${tjskc_version}" #mandatory
displayName="TinkerJS' Kubestruct" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/tinkerjs-kubestruct/" #optional
logoFile="pack.png" #optional
credits="Thanks to Lat, KnightMiner, Max and Dan for all you do with the mods this addon depends on" #optional
authors="ChiefArug" #optional
description='''
Addon integrating parts of Tinkers Construct with KubeJS
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.tinkerjs_kubestruct]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkerjs_kubestruct]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkerjs_kubestruct]]
    modId="tconstruct"
    mandatory=true
    versionRange="${tinkers_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkerjs_kubestruct]]
    modId="kubejs"
    mandatory=true
    versionRange="${kubejs_range}"
    ordering="NONE"
    side="BOTH"